config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  root 'tickets#index'
  post 'api/create_ticket_with_excavator'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_one :excavator
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def create_ticket_with_excavator
    @ticket = Ticket.new
    @ticket.request_number = params["RequestNumber"].presence
    @ticket.sequence_number = params["SequenceNumber"].presence.to_i
    @ticket.request_type = params["RequestType"].presence
    @ticket.request_action = params["RequestAction"].presence
    @ticket.response_due_date_time = params["DateTimes"]["ResponseDueDateTime"].presence
    @ticket.primary_sac = params["ServiceArea"]["PrimaryServiceAreaCode"]["SACode"].presence
    @ticket.additional_sac = params["ServiceArea"]["AdditionalServiceAreaCodes"]["SACode"].presence
    @ticket.dig_site_info = params["DigsiteInfo"]["WellKnownText"].presence

    
    @excavator = Excavator.new
    @excavator.company_name = params["Excavator"]["CompanyName"].presence
    
    @excavator.address = [params["Excavator"]["Address"].presence, params["Excavator"]["City"].presence, params["Excavator"]["State"].presence, params["Excavator"]["Zip"].presence].join(', ')
    @excavator.crew_on_site = params["Excavator"]["CompanyName"].presence.downcase == "true"
    @excavator.save

    @ticket.excavator = @excavator
    @ticket.save
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.joins(:excavators).distinct
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:request_number, :sequence_number, :request_type, :request_action, :response_due_date_time, :primary_sac, :additional_sac, :dig_site_info)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geotest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :request_number, style: "display: block" %>
    <%= form.text_field :request_number %>
  </div>

  <div>
    <%= form.label :sequence_number, style: "display: block" %>
    <%= form.number_field :sequence_number %>
  </div>

  <div>
    <%= form.label :request_type, style: "display: block" %>
    <%= form.text_field :request_type %>
  </div>

  <div>
    <%= form.label :request_action, style: "display: block" %>
    <%= form.text_field :request_action %>
  </div>

  <div>
    <%= form.label :response_due_date_time, style: "display: block" %>
    <%= form.datetime_field :response_due_date_time %>
  </div>

  <div>
    <%= form.label :primary_sac, style: "display: block" %>
    <%= form.text_field :primary_sac %>
  </div>

  <div>
    <%= form.label :additional_sac, style: "display: block" %>
    <%= form.text_field :additional_sac %>
  </div>

  <div>
    <%= form.label :dig_site_info, style: "display: block" %>
    <%= form.text_area :dig_site_info %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Request number:</strong>
    <%= ticket.request_number %>
  </p>

  <p>
    <strong>Sequence number:</strong>
    <%= ticket.sequence_number %>
  </p>

  <p>
    <strong>Request type:</strong>
    <%= ticket.request_type %>
  </p>

  <p>
    <strong>Request action:</strong>
    <%= ticket.request_action %>
  </p>

  <p>
    <strong>Response due date time:</strong>
    <%= ticket.response_due_date_time %>
  </p>

  <p>
    <strong>Primary sac:</strong>
    <%= ticket.primary_sac %>
  </p>

  <p>
    <strong>Additional sac:</strong>
    <%= ticket.additional_sac %>
  </p>

  <p>
    <strong>Dig site info:</strong>
    <%= ticket.dig_site_info %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Request Number</th>
      <th>Sequence Number</th>
      <th>Request Type</th>
      <th>Request Action</th>
      <th>Response Due Date Time</th>
      <th>Primary Service Area Code</th>
      <th>Additional Service Area Codes</th>
      <th>Digsite Info</th>
      <th>Excavator Company Name</th>
      <th>Excavator Address</th>
      <th>Excavator CrewOnSite</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
          <td><%= ticket.request_number %></td>
          <td><%= ticket.sequence_number %></td>
          <td><%= ticket.request_type %></td>
          <td><%= ticket.request_action %></td>
          <td><%= ticket.response_due_date_time %></td>
          <td><%= ticket.primary_sac %></td>
          <td><%= ticket.additional_sac %></td>
          <td><%= ticket.dig_site_info %></td>
          <td><%= ticket.company_name %></td>
          <td><%= ticket.address %></td>
          <td><%= ticket.crew_on_site %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Edit this ticket", edit_ticket_path(@ticket) %> |
  <%= link_to "Back to tickets", tickets_path %>

  <%= button_to "Destroy this ticket", @ticket, method: :delete %>
</div>